In [1]:
import pandas as pd
import re

In [2]:
df_data = pd.read_csv("Asset Challenge/data.csv",encoding='latin1')
df_alay = pd.read_csv("Asset Challenge/new_kamusalay.csv",encoding='latin1',header=None)
df_kasar = pd.read_csv("Asset Challenge/abusive.csv",encoding='latin1')

In [3]:
#Membaca semua dataset yang ada
df_alay=df_alay.rename(columns={0:'Original',1:'Baku'})

df_kasar=pd.read_csv("Asset Challenge/abusive.csv",encoding='latin1')

df_kasar['Kata_Sensor']="53544e534f52" #Inisiasi kata ganti untuk kata-kata yang kasar dengan kata "disensor"

alay_dict_map = dict(zip(df_alay['Original'], df_alay['Baku']))
kasar_dict_map = dict(zip(df_kasar['ABUSIVE'],df_kasar['Kata_Sensor']))

In [4]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from nlp_id.lemmatizer import Lemmatizer 
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

def normalize_alay(text):
    return ' '.join([alay_dict_map[word] if word in alay_dict_map else word for word in text.split(' ')])


def sensor_kata_kasar(text):
    return ' '.join([kasar_dict_map[word] if word in kasar_dict_map else word for word in text.split(' ')])


def preprocess(TextYangInginDiPreProcess):
    #Tahap Pertama Adalah Membuat semua huruf menjadi huruf kecil atau lower
    text = TextYangInginDiPreProcess.lower()

    #Tahap Kedua adalah menghilangkan non alpha numeric character pada text
    text = re.sub('[^0-9a-zA-Z]+',' ',text)

    #Tahap Ketiga adalah menghilangkan char tidak penting
    text=re.sub('\n',' ',text) #Menghilangkan new line pada data
    text=re.sub('rt',' ',text) #Menghilangkan kata-kata retweet 
    text=re.sub('user',' ',text) #Menghilangkan kata-kata user
    text=re.sub('((www\.[^\s]+)|(https?://[^\s]+)|(http?://[^\s]+))',' ',text) #Menghilangkan  URL
    text=re.sub(' +',' ',text) #Menghilangkan ekstra spasi

    #Tahap keempat adalah membuat map terhadap kata-kata "alay" dan mengubah nya menjadi kata yang baku
    text=normalize_alay(text)

    #Tahap kelima adalah mensensor kata kasar dengan kata "disensor"
    text=sensor_kata_kasar(text)
    return text

def menghilangkan_kata_umum_dengan_stopword(text):
    # Mengambil daftar stopwords bahasa Indonesia dari NLTK
    stop_words = set(stopwords.words('indonesian'))
    
    # Memisahkan teks menjadi kata-kata
    words = text.split()
    
    # Menghapus stopwords dari teks
    filtered_words = [word for word in words if word.lower() not in stop_words]
    
    # Menggabungkan kata-kata yang tersisa menjadi teks tanpa stopwords
    filtered_text = ' '.join(filtered_words)
    
    return filtered_text

def mengurangi_variasi_kata_dengan_lematisasi(teks):
    lemmatizer = Lemmatizer() 
    teks = lemmatizer.lemmatize(teks) 
    return teks

def preprocess_semua_kata(teks):
    teks = preprocess(teks)
    teks = menghilangkan_kata_umum_dengan_stopword(teks)
    teks = mengurangi_variasi_kata_dengan_lematisasi(teks)
    return teks

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/raihanekaputra/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [5]:
df_data_1 = df_data.iloc[:2000]
df_data_1

,Tweet,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong
0,- disaat semua cowok berusaha melacak perhatia...,1,1,1,0,0,0,0,0,1,1,0,0
1,RT USER: USER siapa yang telat ngasih tau elu?...,0,1,0,0,0,0,0,0,0,0,0,0
2,"41. Kadang aku berfikir, kenapa aku tetap perc...",0,0,0,0,0,0,0,0,0,0,0,0
3,USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...,0,0,0,0,0,0,0,0,0,0,0,0
4,USER USER Kaum cebong kapir udah keliatan dong...,1,1,0,1,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,USER Ga sekalian lu jadiin gua anak nih biar m...,0,1,0,0,0,0,0,0,0,0,0,0
1996,RT USER: Heran sama orang yang maksa maksa min...,0,0,0,0,0,0,0,0,0,0,0,0
1997,mmg kalo gak pernah turun langsung ke lapangan...,1,1,1,0,0,1,0,0,0,1,0,0
1998,USER USER USER Lebih sadis gerombolan elo saat...,1,1,0,1,0,0,0,0,1,0,1,0
1999,USER namaku sipit ih.\xf0\x9f\x98\xa1',0,0,0,0,0,0,0,0,0,0,0,0

In [6]:
# Menguji Fungsi Untuk Mempreprocess Kata-Kata
kata_kata = "Ini Adalah Anak Anjing"
kata_setelah_di_preprocess = preprocess_semua_kata(kata_kata)
print(kata_setelah_di_preprocess)

anak 53544e534f52

In [7]:
df_data = df_data.head(1000)


df_data['Tweet']=df_data['Tweet'].apply(preprocess_semua_kata)

df_data_1_tweet_hs = df_data[['Tweet','HS']]

df_data_2_tweet_jenis_hs = df_data[['Tweet','HS_Individual','HS_Group',
                                    'HS_Religion','HS_Race','HS_Physical','HS_Gender','HS_Other']]

df_data_3_tweet_kekuatan_hs=df_data[['Tweet','HS_Weak','HS_Moderate','HS_Strong']]

In [8]:
df_data_1_tweet_hs #Dataset yang berfungsi untuk membedakan antara sebuah tweet yang terkategori sebagai hate speech

                                                 Tweet  HS
0    cowok usaha lacak perhati gue lantas remeh per...   1
1    telat tau 53544e534f52 53544e534f52 gue gaul c...   0
2    41 kadang pikir percaya tuhan jatuh kali kali ...   0
3                             ku tau mata 53544e534f52   0
4    kaum 53544e534f52 53544e534f52 dongok 53544e53...   1
..                                                 ...  ..
995         cepat islam nyata sesat sesat bank syariat   1
996  buku langka tuanku rao teror agama islam mazha...   0
997  calon presiden tes urine badan narkotika nasio...   0
998                                  ikut 53544e534f52   1
999  foto bera i sembunyi busa sabun so klin mawar ...   0

[1000 rows x 2 columns]

In [9]:
df_data_2_tweet_jenis_hs

,Tweet,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other
0,cowok usaha lacak perhati gue lantas remeh per...,1,0,0,0,0,0,1
1,telat tau 53544e534f52 53544e534f52 gue gaul c...,0,0,0,0,0,0,0
2,41 kadang pikir percaya tuhan jatuh kali kali ...,0,0,0,0,0,0,0
3,ku tau mata 53544e534f52,0,0,0,0,0,0,0
4,kaum 53544e534f52 53544e534f52 dongok 53544e53...,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...
995,cepat islam nyata sesat sesat bank syariat,0,1,1,0,0,0,0
996,buku langka tuanku rao teror agama islam mazha...,0,0,0,0,0,0,0
997,calon presiden tes urine badan narkotika nasio...,0,0,0,0,0,0,0
998,ikut 53544e534f52,1,0,0,0,0,0,1
999,foto bera i sembunyi busa sabun so klin mawar ...,0,0,0,0,0,0,0

In [10]:
df_data_3_tweet_kekuatan_hs

,Tweet,HS_Weak,HS_Moderate,HS_Strong
0,cowok usaha lacak perhati gue lantas remeh per...,1,0,0
1,telat tau 53544e534f52 53544e534f52 gue gaul c...,0,0,0
2,41 kadang pikir percaya tuhan jatuh kali kali ...,0,0,0
3,ku tau mata 53544e534f52,0,0,0
4,kaum 53544e534f52 53544e534f52 dongok 53544e53...,0,1,0
...,...,...,...,...
995,cepat islam nyata sesat sesat bank syariat,0,1,0
996,buku langka tuanku rao teror agama islam mazha...,0,0,0
997,calon presiden tes urine badan narkotika nasio...,0,0,0
998,ikut 53544e534f52,1,0,0
999,foto bera i sembunyi busa sabun so klin mawar ...,0,0,0

In [11]:
#preprocess_semua_kata((df_data['Tweet']))